# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Ve0qJfmRiSmxrVxIhwy0xn2lbxylw2H
"""

# -*- coding: utf-8 -*-
import pandas as pd
import shapely
from shapely.geometry import Point, shape

from flask import Flask
from flask import render_template
import json

app = Flask(__name__)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/data")
def get_data():
    
    dtypes = {
        'event_id'      : 'float',
        'device_id'     : 'float',
        'year'          : 'float',
        'month'         : 'float',
        'Day_of_week'   : 'float',
        'hour'          : 'float',
        'minute'        : 'float',
        'longitude'     : 'float',
        'latitude'      : 'float',
        'ngender'       : 'float',
        '0-24'          : 'float',
        '25-32'         : 'float',
        '32+'           : 'float'
        }

    train_path = '/home/roshan/Desktop/testing_data_scenario1_age.csv'
    skiprows = None
    nrows = None
    colnames=['event_id','device_id','year','month','Day_of_week','hour','minute','longitude','latitude','ngender','0-24','25-32','32+']

    # read training data
    train_sample = pd.read_csv(train_path, skiprows=skiprows, nrows=nrows, dtype=dtypes, usecols=colnames)

    cols_to_keep = ['timestamp', 'longitude', 'latitude', 'category', 'gender', 'age_group', 'location']
    train_sample_clean = train_sample[cols_to_keep].dropna()
    
    train_sample_clean.to_json(orient='records')

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000, debug=True)
